namespace Exizent.CaseManagement.Client.Models.EstateItems;

public enum GiftRelationshipType
{
    Husband = 1,
    Wife = 2,
    BiologicalChild = 3,
    AdoptedChild = 4,
    StepChild = 5,
    Niece = 6,
    Nephew = 7,
    Sister = 8,
    Brother = 9,
    Mother = 10,
    Father = 11,
    Grandchild = 12,
    GreatGrandchild = 13,
    Cousin = 14,
    Friend = 15,
    Other = 16,
    BrotherInLaw = 17,
    Charity = 18,
    Daughter = 19,
    DaughterInLaw = 20,
    FatherInLaw = 21,
    MotherInLaw = 22,
    Organisation = 23,
    Partner = 24,
    SisterInLaw = 25,
    Solicitor = 26,
    Son = 27,
    SonInLaw = 28,
    BusinessPartner = 29,
    CivilPartner = 30,
    Spouse = 31,
}